/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package theprison.gui;

import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Jamemez
 */
public class Add_Visit extends javax.swing.JFrame {
  Prison_login login = new Prison_login();
    private long staffId = login.staffId;
    Process process = new Process();
    /**
     * Creates new form Add_Visit
     */
    public Add_Visit() {
        initComponents();
        this.setSize(400, 400);
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        String date = df.format(cal.getTime());
        Staff staff = process.checkOwner(staffId);
        this.labelSName.setText(staff.getS_name());
        this.labeldate.setText(String.valueOf(date));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelSName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        labeldate = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pri_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Staff Name :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 30, 90, 30);
        getContentPane().add(labelSName);
        labelSName.setBounds(110, 30, 230, 30);

        jLabel2.setText("Visitor Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 110, 90, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(110, 110, 210, 30);

        jLabel3.setText("Visitor ID Card :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 150, 90, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(110, 150, 210, 30);

        jLabel4.setText("Visitor Date :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 200, 90, 40);
        getContentPane().add(labeldate);
        labeldate.setBounds(120, 200, 150, 40);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 260, 100, 40);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 260, 110, 40);

        jLabel5.setText("Prisoner ID :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 70, 90, 30);
        getContentPane().add(pri_id);
        pri_id.setBounds(110, 70, 210, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(this.jTextField1.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Enter Name");
        }
        else{
            if(this.jTextField2.getText().equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(this, "Enter ID Card");
            }
            else {
                  Calendar cal = Calendar.getInstance();
               process.submitVisitor(staffId, this.jTextField1.getText(),Integer.decode(this.jTextField2.getText()),cal.getTime(),Long.decode(this.pri_id.getText()));
               JOptionPane.showMessageDialog(this, "Submit Complete");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Main_Program main = new Main_Program();
        main.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Visit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Visit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Visit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Visit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Visit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel labelSName;
    private javax.swing.JLabel labeldate;
    private javax.swing.JTextField pri_id;
    // End of variables declaration//GEN-END:variables
}
