/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package theprison.gui;

import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Jamemez
 */
public class Info_Prisoner extends javax.swing.JFrame {
     Prison_login login = new Prison_login();
    private long staffId = login.staffId;
    Process process = new Process();
    Prisoner_Program pp = new Prisoner_Program();
    Detail_Prisoner de_pri = pp.de_pri;
    /**
     * Creates new form Info_Prisoner
     */
    public Info_Prisoner() {
        initComponents();
        this.setSize(550, 500);
        this.setLocationRelativeTo(null);
    
        this.show_id.setText(String.valueOf(de_pri.getId_prisoner()));
        this.show_name.setText(String.valueOf(de_pri.getName_prisoner()));
        this.show_age.setText(String.valueOf(de_pri.getAge()));
        this.show_ministry.setText(String.valueOf(de_pri.isMinistry_status()));
        this.show_penaltyID.setText(String.valueOf(de_pri.getId_penalty()));
        this.show_status.setText(Process.getStatusByIdPri(de_pri.getId_prisoner()));
        this.crime_name.setText(de_pri.getCrime());
        this.show_crimeID.setText(String.valueOf(de_pri.getCrime_id()));
        this.show_penal_name.setText(de_pri.getPenalty());
        this.show_penalty_detail.setText(de_pri.getPenalty_detail());
        this.crime_name.setText(de_pri.getCrime());
        this.crime_detail.setText(de_pri.getCrime_detail());
        this.in_date.setText(String.valueOf(de_pri.getIndate()));
        this.out_date.setText(String.valueOf(de_pri.getOutDate()));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        show_name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        show_age = new javax.swing.JLabel();
        show_ministry = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        show_id = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        show_penaltyID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        show_penalty_detail = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        crime_detail = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        show_status = new javax.swing.JLabel();
        show_crimeID = new javax.swing.JLabel();
        show_penal_name = new javax.swing.JLabel();
        crime_name = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        in_date = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        out_date = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Name :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 80, 60, 29);
        getContentPane().add(show_name);
        show_name.setBounds(70, 80, 320, 29);

        jLabel2.setText("Ministry Status :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 120, 91, 31);

        jLabel3.setText("Age :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 90, 65, 26);
        getContentPane().add(show_age);
        show_age.setBounds(440, 90, 56, 29);
        getContentPane().add(show_ministry);
        show_ministry.setBounds(110, 120, 80, 31);

        jLabel4.setText("Penalty ID :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 160, 100, 32);

        jLabel6.setText("ID Prisoner :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 40, 77, 33);
        getContentPane().add(show_id);
        show_id.setBounds(110, 40, 200, 33);

        jLabel5.setText("Status :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(350, 40, 60, 33);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Prisoner Detail");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(200, 0, 180, 40);

        jLabel8.setText("Crime ID :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 280, 80, 30);

        jLabel9.setText("Note : Penalty***");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(410, 160, 100, 30);

        jLabel10.setText("Note : Crime***");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(380, 280, 130, 30);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 400, 100, 30);

        jButton2.setText("Save");
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 400, 110, 30);

        show_penaltyID.setEditable(false);
        getContentPane().add(show_penaltyID);
        show_penaltyID.setBounds(130, 160, 110, 30);

        show_penalty_detail.setEditable(false);
        show_penalty_detail.setColumns(20);
        show_penalty_detail.setLineWrap(true);
        show_penalty_detail.setRows(5);
        jScrollPane1.setViewportView(show_penalty_detail);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 200, 450, 70);

        crime_detail.setEditable(false);
        crime_detail.setColumns(20);
        crime_detail.setLineWrap(true);
        crime_detail.setRows(5);
        jScrollPane2.setViewportView(crime_detail);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 320, 450, 70);

        jButton4.setText("Add Penalty");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(150, 400, 110, 30);

        jButton5.setText("Add Crime");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(270, 400, 100, 30);
        getContentPane().add(show_status);
        show_status.setBounds(410, 40, 80, 40);
        getContentPane().add(show_crimeID);
        show_crimeID.setBounds(120, 284, 120, 30);
        getContentPane().add(show_penal_name);
        show_penal_name.setBounds(260, 160, 130, 30);
        getContentPane().add(crime_name);
        crime_name.setBounds(260, 280, 110, 30);

        jLabel11.setText("In Date :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(210, 120, 60, 40);
        getContentPane().add(in_date);
        in_date.setBounds(260, 120, 90, 40);

        jLabel12.setText("Out Date :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(370, 120, 60, 40);
        getContentPane().add(out_date);
        out_date.setBounds(430, 120, 90, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           this.setVisible(false);
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Add_Penalty penal = new Add_Penalty();
        penal.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Add_Crime cri = new Add_Crime();
        cri.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Info_Prisoner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Info_Prisoner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Info_Prisoner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Info_Prisoner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Info_Prisoner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea crime_detail;
    private javax.swing.JLabel crime_name;
    private javax.swing.JLabel in_date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel out_date;
    private javax.swing.JLabel show_age;
    private javax.swing.JLabel show_crimeID;
    private javax.swing.JLabel show_id;
    private javax.swing.JLabel show_ministry;
    private javax.swing.JLabel show_name;
    private javax.swing.JLabel show_penal_name;
    private javax.swing.JTextField show_penaltyID;
    private javax.swing.JTextArea show_penalty_detail;
    private javax.swing.JLabel show_status;
    // End of variables declaration//GEN-END:variables
}
