/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package theprison.gui;

import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Jamemez
 */
public class Search_Program extends javax.swing.JFrame {

    Process process = new Process();

    /**
     * Creates new form Search_Program
     */
    public Search_Program() {
        initComponents();
        this.setSize(700, 550);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(484, 11, 87, 40);

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(580, 10, 80, 40);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(10, 11, 456, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Position"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(21, 101, 644, 370);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setMnemonic('1');
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Warden");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(190, 60, 90, 23);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setMnemonic('2');
        jRadioButton3.setText("Staff");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(300, 60, 70, 23);

        jLabel1.setText("Type person :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 57, 140, 26);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(490, 60, 100, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.jTextField1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Vector vec = new Vector();
        vec.add("ID");
        vec.add("Name");
        vec.add("Position");
        TableModel model1 = new DefaultTableModel(vec,0);
        this.jTable1.setModel(model1);
        if (this.jTextField1.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Please input keywork for search");
        } else if (this.jRadioButton2.isSelected() || this.jRadioButton3.isSelected()) {
            if (this.buttonGroup1.getSelection().getMnemonic() == 49) {
                ArrayList<Warden> wardens = process.getSearchWarden(this.jTextField1.getText());

                if (wardens != null) {
                    TableModel model = new DefaultTableModel(vec, wardens.size());
                    this.jTable1.setModel(model);

                    for (int i = 0; i < wardens.size(); i++) {
                        this.jTable1.setValueAt(wardens.get(i).getId_warden(), i, 0);
                        this.jTable1.setValueAt(wardens.get(i).getName_warden(), i, 1);
                        this.jTable1.setValueAt(wardens.get(i).getW_position(), i, 2);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Not found result");
                }
            } else if (this.buttonGroup1.getSelection().getMnemonic() == 50) {
                ArrayList<Staff> staffs = process.getSearchStaff(this.jTextField1.getText());

                if (staffs != null) {
                    TableModel model = new DefaultTableModel(vec, staffs.size());
                    this.jTable1.setModel(model);

                    for (int i = 0; i < staffs.size(); i++) {
                        this.jTable1.setValueAt(staffs.get(i).getId_staff(), i, 0);
                        this.jTable1.setValueAt(staffs.get(i).getS_name(), i, 1);
                        this.jTable1.setValueAt(staffs.get(i).getS_position(), i, 2);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Not found result");
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Main_Program main = new Main_Program();
        main.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_Program().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
